-- Porra Live v1 no activa cap cron ni consumeix API-Football automàticament.
--
-- La sincronització és opcional i es configura per porra mitjançant
-- match_states.provider_fixture_id. Abans de programar-la en una versió futura:
-- 1. desa SYNC_SECRET a Edge Functions Secrets i Supabase Vault;
-- 2. limita les crides a la finestra real del partit;
-- 3. envia poolId al cos i x-sync-secret a la capçalera;
-- 4. mantén sempre disponibles els controls manuals.
--
-- Aquest fitxer és deliberadament no executable per evitar activar consum extern
-- o una URL de projecte concreta des del repositori.
